from typing import Protocol

import pandas as pd

from MagmaPandas.core.enums import Datatype, Unit


class Magma(Protocol):
    _units: Unit
    _datatype: Datatype
    _weights: pd.Series

    @property
    def _no_data(self): ...

    @property
    def _total(self): ...

    @property
    def units(self): ...

    @property
    def weights(self): ...

    @property
    def elements(self): ...

    @property
    def ppm(self): ...

    @property
    def oxygen(self): ...

    def moles(self): ...

    def wt_pc(self): ...

    def cations(self): ...

    def convert_ppm_wtPercent(self): ...

    def _convert_moles_wtPercent(self): ...

    def oxides(self): ...

    def recalculate(self): ...

    def normalise(self): ...

    def random_sample(self): ...

    def mineral_formula(self): ...
