from MagmaPandas.volatile_solubility.models import Shiskina
from MagmaPandas.volatile_solubility.models import Allison2022
from MagmaPandas.volatile_solubility.models import IaconoMarziano
from MagmaPandas.volatile_solubility.models.solubility_baseclass import *